version: "3.9"
services:
  subscriber:
    build:
      context: .
      target: subscriber
    networks:
      - msg_net
    depends_on:
      - broker
  publisher:
    build:
      context: .
      target: publisher
    networks:
      - msg_net
    depends_on:
      - broker
  broker:
    build:
      context: .
      target: broker
    networks:
      - msg_net
networks:
  msg_net:
    name: msg_net